using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations.Schema;

namespace fortniteLib.Responses.Pvp
{
    public class BattleRoyaleStats
    {
        public int startTime { get; set; }
        public long endTime { get; set; }
        public JObject stats { get; set; }
        public string accountId { get; set; }

        [JsonIgnore]
        [NotMapped]
        public bool IsPrivate { get; set; }
    }

    public class Stats
    {
        public int br_playersoutlived_keyboardmouse_m0_playlist_defaultduo { get; set; }
        public int br_minutesplayed_keyboardmouse_m0_playlist_respawn_24 { get; set; }
        public int br_placetop5_keyboardmouse_m0_playlist_deimos_duoshow { get; set; }
        public int br_playersoutlived_keyboardmouse_m0_playlist_toss_squads { get; set; }
        public int br_placetop6_keyboardmouse_m0_playlist_classic_squads { get; set; }
        public int br_matchesplayed_keyboardmouse_m0_playlist_trios { get; set; }
        public int br_minutesplayed_keyboardmouse_m0_playlist_deimos_solo_winter { get; set; }
        public int br_placetop1_keyboardmouse_m0_playlist_50v50 { get; set; }
        public int br_playersoutlived_keyboardmouse_m0_playlist_close_solo { get; set; }
        public int br_placetop5_keyboardmouse_m0_playlist_snipers_duos { get; set; }
        public int br_placetop3_keyboardmouse_m0_playlist_sword_squads { get; set; }
        public int br_placetop5_keyboardmouse_m0_playlist_deimos_duo_winter { get; set; }
        public int br_placetop3_keyboardmouse_m0_playlist_bling_squads { get; set; }
        public int br_playersoutlived_keyboardmouse_m0_playlist_deimos_solo_winter { get; set; }
        public int br_matchesplayed_keyboardmouse_m0_playlist_close_duos { get; set; }
        public int br_minutesplayed_keyboardmouse_m0_playlist_toss_squads { get; set; }
        public int br_playersoutlived_keyboardmouse_m0_playlist_deimos_squad_winter { get; set; }
        public int br_placetop3_keyboardmouse_m0_playlist_solidgold_squads { get; set; }
        public int br_matchesplayed_keyboardmouse_m0_playlist_deimos_duo_winter { get; set; }
        public int br_placetop10_keyboardmouse_m0_playlist_showdown_solo { get; set; }
        public int br_lastmodified_keyboardmouse_m0_playlist_close_duos { get; set; }
        public int br_minutesplayed_keyboardmouse_m0_playlist_defaultsquad { get; set; }
        public int br_kills_keyboardmouse_m0_playlist_hover_64 { get; set; }
        public int br_score_keyboardmouse_m0_playlist_toss_squads { get; set; }
        public int br_minutesplayed_keyboardmouse_m0_playlist_sword_squads { get; set; }
        public int br_matchesplayed_keyboardmouse_m0_playlist_bling_squads { get; set; }
        public int br_placetop6_keyboardmouse_m0_playlist_close_squad { get; set; }
        public int br_score_keyboardmouse_m0_playlist_classic_squads { get; set; }
        public int br_kills_keyboardmouse_m0_playlist_flyexplosives_squads { get; set; }
        public int br_placetop1_keyboardmouse_m0_playlist_toss_squads { get; set; }
        public int br_minutesplayed_keyboardmouse_m0_playlist_music_high { get; set; }
        public int br_playersoutlived_keyboardmouse_m0_playlist_snipers_duos { get; set; }
        public int br_minutesplayed_keyboardmouse_m0_playlist_deimos_duo_winter { get; set; }
        public int br_matchesplayed_keyboardmouse_m0_playlist_solidgold_solo { get; set; }
        public int br_minutesplayed_keyboardmouse_m0_playlist_defaultduo { get; set; }
        public int br_playersoutlived_keyboardmouse_m0_playlist_respawn_24 { get; set; }
        public int br_kills_keyboardmouse_m0_playlist_final_20 { get; set; }
        public int br_placetop25_keyboardmouse_m0_playlist_deimos_solo_winter { get; set; }
        public int br_matchesplayed_keyboardmouse_m0_playlist_final_20 { get; set; }
        public int br_score_keyboardmouse_m0_playlist_defaultsquad { get; set; }
        public int br_score_keyboardmouse_m0_playlist_close_duos { get; set; }
        public int br_placetop3_keyboardmouse_m0_playlist_defaultsquad { get; set; }
        public int br_placetop12_keyboardmouse_m0_playlist_deimos_duo { get; set; }
        public int br_kills_keyboardmouse_m0_playlist_deimos_duo_winter { get; set; }
        public int br_placetop6_keyboardmouse_m0_playlist_steady_squads { get; set; }
        public int br_kills_keyboardmouse_m0_playlist_classic_squads { get; set; }
        public int br_matchesplayed_keyboardmouse_m0_playlist_deimos_solo_winter { get; set; }
        public int br_placetop10_keyboardmouse_m0_playlist_deimos_solo_winter { get; set; }
        public int br_kills_keyboardmouse_m0_playlist_slide_squads { get; set; }
        public int br_minutesplayed_keyboardmouse_m0_playlist_solidgold_squads { get; set; }
        public int br_lastmodified_keyboardmouse_m0_playlist_defaultsquad { get; set; }
        public int br_placetop1_keyboardmouse_m0_playlist_defaultsquad { get; set; }
        public int br_kills_keyboardmouse_m0_playlist_final_12 { get; set; }
        public int br_score_keyboardmouse_m0_playlist_love_duos { get; set; }
        public int br_matchesplayed_keyboardmouse_m0_playlist_sword_squads { get; set; }
        public int br_kills_keyboardmouse_m0_playlist_33 { get; set; }
        public int br_placetop1_keyboardmouse_m0_playlist_playground { get; set; }
        public int br_playersoutlived_keyboardmouse_m0_playlist_solidgold_squads { get; set; }
        public int br_placetop1_keyboardmouse_m0_playlist_5x20 { get; set; }
        public int br_matchesplayed_keyboardmouse_m0_playlist_solidgold_squads { get; set; }
        public int br_kills_keyboardmouse_m0_playlist_steady_squads { get; set; }
        public int br_matchesplayed_keyboardmouse_m0_playlist_final_12 { get; set; }
        public int br_minutesplayed_keyboardmouse_m0_playlist_close_solo { get; set; }
        public int br_kills_keyboardmouse_m0_playlist_50v50he { get; set; }
        public int br_placetop1_keyboardmouse_m0_playlist_steady_squads { get; set; }
        public int br_playersoutlived_keyboardmouse_m0_playlist_33 { get; set; }
        public int br_playersoutlived_keyboardmouse_m0_playlist_trios { get; set; }
        public int br_kills_keyboardmouse_m0_playlist_showdown_solo { get; set; }
        public int br_matchesplayed_keyboardmouse_m0_playlist_50v50 { get; set; }
        public int br_placetop3_keyboardmouse_m0_playlist_deimos_squad { get; set; }
        public int br_kills_keyboardmouse_m0_playlist_50v50 { get; set; }
        public int br_matchesplayed_keyboardmouse_m0_playlist_deimos_50 { get; set; }
        public int br_placetop6_keyboardmouse_m0_playlist_deimos_squad { get; set; }
        public int br_placetop25_keyboardmouse_m0_playlist_showdown_solo { get; set; }
        public int br_lastmodified_keyboardmouse_m0_playlist_deimos_duo_winter { get; set; }
        public int br_placetop1_keyboardmouse_m0_playlist_50v50sau { get; set; }
        public int br_placetop1_keyboardmouse_m0_playlist_deimos_duo_winter { get; set; }
        public int br_playersoutlived_keyboardmouse_m0_playlist_playgroundv2 { get; set; }
        public int br_kills_keyboardmouse_m0_playlist_disco { get; set; }
        public int br_placetop12_keyboardmouse_m0_playlist_defaultduo { get; set; }
        public int br_placetop3_keyboardmouse_m0_playlist_flyexplosives_squads { get; set; }
        public int br_lastmodified_keyboardmouse_m0_playlist_sword_squads { get; set; }
        public int br_minutesplayed_keyboardmouse_m0_playlist_low_squads { get; set; }
        public int br_playersoutlived_keyboardmouse_m0_playlist_hover_64 { get; set; }
        public int br_minutesplayed_keyboardmouse_m0_playlist_deimos_squad_winter { get; set; }
        public int br_placetop5_keyboardmouse_m0_playlist_love_duos { get; set; }
        public int br_placetop10_keyboardmouse_m0_playlist_close_solo { get; set; }
        public int br_kills_keyboardmouse_m0_playlist_highexplosives_squads { get; set; }
        public int br_matchesplayed_keyboardmouse_m0_playlist_ground_squads { get; set; }
        public int br_kills_keyboardmouse_m0_playlist_deimos_squad { get; set; }
        public int br_kills_keyboardmouse_m0_playlist_low_squads { get; set; }
        public int br_kills_keyboardmouse_m0_playlist_playgroundv2 { get; set; }
        public int br_kills_keyboardmouse_m0_playlist_50v50sau { get; set; }
        public int br_score_keyboardmouse_m0_playlist_deimos_duo_winter { get; set; }
        public int br_lastmodified_keyboardmouse_m0_playlist_low_squads { get; set; }
        public int br_matchesplayed_keyboardmouse_m0_playlist_snipers_duos { get; set; }
        public int br_placetop3_keyboardmouse_m0_playlist_steady_squads { get; set; }
        public int br_kills_keyboardmouse_m0_playlist_solidgold_squads { get; set; }
        public int br_matchesplayed_keyboardmouse_m0_playlist_deimos_duoshow { get; set; }
        public int br_matchesplayed_keyboardmouse_m0_playlist_defaultsquad { get; set; }
        public int br_matchesplayed_keyboardmouse_m0_playlist_disco { get; set; }
        public int br_placetop3_keyboardmouse_m0_playlist_toss_squads { get; set; }
        public int br_matchesplayed_keyboardmouse_m0_playlist_score_duos { get; set; }
        public int br_kills_keyboardmouse_m0_playlist_trios { get; set; }
        public int br_lastmodified_keyboardmouse_m0_playlist_highexplosives_squads { get; set; }
        public int br_placetop6_keyboardmouse_m0_playlist_solidgold_squads { get; set; }
        public int br_placetop3_keyboardmouse_m0_playlist_blitz_squad { get; set; }
        public int br_lastmodified_keyboardmouse_m0_playlist_close_squad { get; set; }
        public int br_placetop1_keyboardmouse_m0_playlist_50v50he { get; set; }
        public int br_minutesplayed_keyboardmouse_m0_playlist_playgroundv2 { get; set; }
        public int br_matchesplayed_keyboardmouse_m0_playlist_playground { get; set; }
        public int br_matchesplayed_keyboardmouse_m0_playlist_hover_64 { get; set; }
        public int br_matchesplayed_keyboardmouse_m0_playlist_disco_32 { get; set; }
        public int br_placetop25_keyboardmouse_m0_playlist_close_solo { get; set; }
        public int br_kills_keyboardmouse_m0_playlist_showdown_squads { get; set; }
        public int br_kills_keyboardmouse_m0_playlist_deimos_solo_winter { get; set; }
        public int br_placetop3_keyboardmouse_m0_playlist_hard_squads { get; set; }
        public int br_matchesplayed_keyboardmouse_m0_playlist_close_solo { get; set; }
        public int br_placetop3_keyboardmouse_m0_playlist_deimos_squad_winter { get; set; }
        public int br_matchesplayed_keyboardmouse_m0_playlist_classic_squads { get; set; }
        public int br_placetop5_keyboardmouse_m0_playlist_defaultduo { get; set; }
        public int br_placetop1_keyboardmouse_m0_playlist_disco_32 { get; set; }
        public int br_placetop12_keyboardmouse_m0_playlist_flyexplosives_duos { get; set; }
        public int br_placetop1_keyboardmouse_m0_playlist_defaultduo { get; set; }
        public int br_placetop1_keyboardmouse_m0_playlist_highexplosives_squads { get; set; }
        public int br_minutesplayed_keyboardmouse_m0_playlist_love_duos { get; set; }
        public int br_matchesplayed_keyboardmouse_m0_playlist_love_duos { get; set; }
        public int br_kills_keyboardmouse_m0_playlist_love_duos { get; set; }
        public int br_minutesplayed_keyboardmouse_m0_playlist_close_duos { get; set; }
        public int br_kills_keyboardmouse_m0_playlist_flyexplosives_duos { get; set; }
        public int br_matchesplayed_keyboardmouse_m0_playlist_deimos_duo { get; set; }
        public int br_placetop12_keyboardmouse_m0_playlist_deimos_duoshow { get; set; }
        public int br_score_keyboardmouse_m0_playlist_defaultduo { get; set; }
        public int br_lastmodified_keyboardmouse_m0_playlist_deimos_solo_winter { get; set; }
        public int br_placetop10_keyboardmouse_m0_playlist_defaultsolo { get; set; }
        public int br_score_keyboardmouse_m0_playlist_highexplosives_squads { get; set; }
        public int br_playersoutlived_keyboardmouse_m0_playlist_close_squad { get; set; }
        public int br_playersoutlived_keyboardmouse_m0_playlist_deimos_duo_winter { get; set; }
        public int br_score_keyboardmouse_m0_playlist_deimos_squad_winter { get; set; }
        public int br_kills_keyboardmouse_m0_playlist_barrier_12 { get; set; }
        public int br_minutesplayed_keyboardmouse_m0_playlist_classic_squads { get; set; }
        public int br_kills_keyboardmouse_m0_playlist_bling_squads { get; set; }
        public int br_score_keyboardmouse_m0_playlist_snipers_duos { get; set; }
        public int br_kills_keyboardmouse_m0_playlist_sword_squads { get; set; }
        public int br_kills_keyboardmouse_m0_playlist_respawn_24 { get; set; }
        public int br_kills_keyboardmouse_m0_playlist_close_squad { get; set; }
        public int br_lastmodified_keyboardmouse_m0_playlist_snipers_duos { get; set; }
        public int br_lastmodified_keyboardmouse_m0_playlist_love_duos { get; set; }
        public int br_kills_keyboardmouse_m0_playlist_deimos_squad_winter { get; set; }
        public int br_matchesplayed_keyboardmouse_m0_playlist_barrier_12 { get; set; }
        public int br_placetop1_keyboardmouse_m0_playlist_deimos_squad { get; set; }
        public int br_kills_keyboardmouse_m0_playlist_solidgold_solo { get; set; }
        public int br_lastmodified_keyboardmouse_m0_playlist_music_high { get; set; }
        public int br_score_keyboardmouse_m0_playlist_playgroundv2 { get; set; }
        public int br_kills_keyboardmouse_m0_playlist_ground_squads { get; set; }
        public int br_matchesplayed_keyboardmouse_m0_playlist_music_high { get; set; }
        public int br_placetop6_keyboardmouse_m0_playlist_defaultsquad { get; set; }
        public int br_playersoutlived_keyboardmouse_m0_playlist_classic_squads { get; set; }
        public int br_score_keyboardmouse_m0_playlist_defaultsolo { get; set; }
        public int br_score_keyboardmouse_m0_playlist_blitz_squad { get; set; }
        public int br_score_keyboardmouse_m0_playlist_close_solo { get; set; }
        public int br_placetop12_keyboardmouse_m0_playlist_snipers_duos { get; set; }
        public int br_kills_keyboardmouse_m0_playlist_deimos_50 { get; set; }
        public int br_placetop12_keyboardmouse_m0_playlist_deimos_duo_winter { get; set; }
        public int br_kills_keyboardmouse_m0_playlist_music_high { get; set; }
        public int br_placetop3_keyboardmouse_m0_playlist_classic_squads { get; set; }
        public int br_placetop1_keyboardmouse_m0_playlist_flyexplosives_duos { get; set; }
        public int br_playersoutlived_keyboardmouse_m0_playlist_highexplosives_squads { get; set; }
        public int br_score_keyboardmouse_m0_playlist_33 { get; set; }
        public int br_placetop1_keyboardmouse_m0_playlist_solidgold_squads { get; set; }
        public int br_placetop1_keyboardmouse_m0_playlist_blitz_squad { get; set; }
        public int br_lastmodified_keyboardmouse_m0_playlist_playgroundv2 { get; set; }
        public int br_matchesplayed_keyboardmouse_m0_playlist_respawn_24 { get; set; }
        public int br_placetop1_keyboardmouse_m0_playlist_low_squads { get; set; }
        public int br_placetop1_keyboardmouse_m0_playlist_defaultsolo { get; set; }
        public int br_score_keyboardmouse_m0_playlist_trios { get; set; }
        public int br_lastmodified_keyboardmouse_m0_playlist_respawn_24 { get; set; }
        public int br_matchesplayed_keyboardmouse_m0_playlist_slide_squads { get; set; }
        public int br_minutesplayed_keyboardmouse_m0_playlist_close_squad { get; set; }
        public int br_kills_keyboardmouse_m0_playlist_defaultsquad { get; set; }
        public int br_playersoutlived_keyboardmouse_m0_playlist_blitz_squad { get; set; }
        public int br_lastmodified_keyboardmouse_m0_playlist_defaultduo { get; set; }
        public int br_playersoutlived_keyboardmouse_m0_playlist_love_duos { get; set; }
        public int br_playersoutlived_keyboardmouse_m0_playlist_defaultsolo { get; set; }
        public int br_matchesplayed_keyboardmouse_m0_playlist_deimos_solo { get; set; }
        public int br_score_keyboardmouse_m0_playlist_music_high { get; set; }
        public int br_matchesplayed_keyboardmouse_m0_playlist_5x20 { get; set; }
        public int br_placetop6_keyboardmouse_m0_playlist_low_squads { get; set; }
        public int br_matchesplayed_keyboardmouse_m0_playlist_defaultduo { get; set; }
        public int br_placetop6_keyboardmouse_m0_playlist_bling_squads { get; set; }
        public int br_kills_keyboardmouse_m0_playlist_defaultduo { get; set; }
        public int br_placetop6_keyboardmouse_m0_playlist_highexplosives_squads { get; set; }
        public int br_placetop25_keyboardmouse_m0_playlist_solidgold_solo { get; set; }
        public int br_score_keyboardmouse_m0_playlist_close_squad { get; set; }
        public int br_placetop12_keyboardmouse_m0_playlist_love_duos { get; set; }
        public int br_playersoutlived_keyboardmouse_m0_playlist_defaultsquad { get; set; }
        public int br_playersoutlived_keyboardmouse_m0_playlist_low_squads { get; set; }
        public int br_placetop6_keyboardmouse_m0_playlist_flyexplosives_squads { get; set; }
        public int br_kills_keyboardmouse_m0_playlist_close_solo { get; set; }
        public int br_placetop1_keyboardmouse_m0_playlist_deimos_squad_winter { get; set; }
        public int br_placetop3_keyboardmouse_m0_playlist_low_squads { get; set; }
        public int br_kills_keyboardmouse_m0_playlist_soaring_50s { get; set; }
        public int br_placetop1_keyboardmouse_m0_playlist_love_duos { get; set; }
        public int br_matchesplayed_keyboardmouse_m0_playlist_flyexplosives_duos { get; set; }
        public int br_playersoutlived_keyboardmouse_m0_playlist_close_duos { get; set; }
        public int br_minutesplayed_keyboardmouse_m0_playlist_snipers_duos { get; set; }
        public int br_placetop1_keyboardmouse_m0_playlist_deimos_duoshow { get; set; }
        public int br_matchesplayed_keyboardmouse_m0_playlist_close_squad { get; set; }
        public int br_matchesplayed_keyboardmouse_m0_playlist_soaring_50s { get; set; }
        public int br_lastmodified_keyboardmouse_m0_playlist_33 { get; set; }
        public int br_kills_keyboardmouse_m0_playlist_deimos_solo { get; set; }
        public int br_lastmodified_keyboardmouse_m0_playlist_trios { get; set; }
        public int br_placetop3_keyboardmouse_m0_playlist_close_squad { get; set; }
        public int br_score_keyboardmouse_m0_playlist_playground { get; set; }
        public int br_minutesplayed_keyboardmouse_m0_playlist_33 { get; set; }
        public int br_kills_keyboardmouse_m0_playlist_deimos_duo { get; set; }
        public int br_placetop1_keyboardmouse_m0_playlist_bling_squads { get; set; }
        public int br_kills_keyboardmouse_m0_playlist_snipers { get; set; }
        public int br_matchesplayed_keyboardmouse_m0_playlist_deimos_squad_winter { get; set; }
        public int br_minutesplayed_keyboardmouse_m0_playlist_playground { get; set; }
        public int br_kills_keyboardmouse_m0_playlist_hard_squads { get; set; }
        public int br_placetop6_keyboardmouse_m0_playlist_hard_squads { get; set; }
        public int br_matchesplayed_keyboardmouse_m0_playlist_showdown_solo { get; set; }
        public int br_matchesplayed_keyboardmouse_m0_playlist_33 { get; set; }
        public int br_placetop6_keyboardmouse_m0_playlist_deimos_squad_winter { get; set; }
        public int br_playersoutlived_keyboardmouse_m0_playlist_sword_squads { get; set; }
        public int br_score_keyboardmouse_m0_playlist_low_squads { get; set; }
        public int br_placetop5_keyboardmouse_m0_playlist_flyexplosives_duos { get; set; }
        public int br_placetop5_keyboardmouse_m0_playlist_deimos_duo { get; set; }
        public int br_kills_keyboardmouse_m0_playlist_snipers_duos { get; set; }
        public int br_kills_keyboardmouse_m0_playlist_playground { get; set; }
        public int br_placetop1_keyboardmouse_m0_playlist_final_20 { get; set; }
        public int br_score_keyboardmouse_m0_playlist_sword_squads { get; set; }
        public int br_lastmodified_keyboardmouse_m0_playlist_deimos_squad_winter { get; set; }
        public int br_placetop6_keyboardmouse_m0_playlist_showdown_squads { get; set; }
        public int br_placetop1_keyboardmouse_m0_playlist_classic_squads { get; set; }
        public int br_playersoutlived_keyboardmouse_m0_playlist_hard_squads { get; set; }
        public int br_matchesplayed_keyboardmouse_m0_playlist_low_squads { get; set; }
        public int br_score_keyboardmouse_m0_playlist_hover_64 { get; set; }
        public int br_kills_keyboardmouse_m0_playlist_disco_32 { get; set; }
        public int br_playersoutlived_keyboardmouse_m0_playlist_music_high { get; set; }
        public int br_matchesplayed_keyboardmouse_m0_playlist_blitz_squad { get; set; }
        public int br_lastmodified_keyboardmouse_m0_playlist_classic_squads { get; set; }
        public int br_placetop25_keyboardmouse_m0_playlist_defaultsolo { get; set; }
        public int br_matchesplayed_keyboardmouse_m0_playlist_toss_squads { get; set; }
        public int br_placetop1_keyboardmouse_m0_playlist_final_12 { get; set; }
        public int br_lastmodified_keyboardmouse_m0_playlist_playground { get; set; }
        public int br_matchesplayed_keyboardmouse_m0_playlist_snipers { get; set; }
        public int br_matchesplayed_keyboardmouse_m0_playlist_flyexplosives_squads { get; set; }
        public int br_matchesplayed_keyboardmouse_m0_playlist_defaultsolo { get; set; }
        public int br_lastmodified_keyboardmouse_m0_playlist_hover_64 { get; set; }
        public int br_matchesplayed_keyboardmouse_m0_playlist_playgroundv2 { get; set; }
        public int br_matchesplayed_keyboardmouse_m0_playlist_deimos_squad { get; set; }
        public int br_score_keyboardmouse_m0_playlist_hard_squads { get; set; }
        public int br_score_keyboardmouse_m0_playlist_solidgold_squads { get; set; }
        public int br_minutesplayed_keyboardmouse_m0_playlist_trios { get; set; }
        public int br_placetop6_keyboardmouse_m0_playlist_sword_squads { get; set; }
        public int br_lastmodified_keyboardmouse_m0_playlist_solidgold_squads { get; set; }
        public int br_lastmodified_keyboardmouse_m0_playlist_close_solo { get; set; }
        public int br_matchesplayed_keyboardmouse_m0_playlist_hard_squads { get; set; }
        public int br_lastmodified_keyboardmouse_m0_playlist_defaultsolo { get; set; }
        public int br_matchesplayed_keyboardmouse_m0_playlist_showdown_squads { get; set; }
        public int br_minutesplayed_keyboardmouse_m0_playlist_hard_squads { get; set; }
        public int br_placetop1_keyboardmouse_m0_playlist_respawn_24 { get; set; }
        public int br_lastmodified_keyboardmouse_m0_playlist_blitz_squad { get; set; }
        public int br_lastmodified_keyboardmouse_m0_playlist_hard_squads { get; set; }
        public int br_kills_keyboardmouse_m0_playlist_5x20 { get; set; }
        public int br_matchesplayed_touch_m0_playlist_defaultsquad { get; set; }
        public int br_lastmodified_keyboardmouse_m0_playlist_toss_squads { get; set; }
        public int br_placetop1_keyboardmouse_m0_playlist_deimos_50 { get; set; }
        public int br_minutesplayed_keyboardmouse_m0_playlist_hover_64 { get; set; }
        public int br_minutesplayed_keyboardmouse_m0_playlist_highexplosives_squads { get; set; }
        public int br_placetop1_keyboardmouse_m0_playlist_soaring_50s { get; set; }
        public int br_kills_keyboardmouse_m0_playlist_toss_squads { get; set; }
        public int br_score_keyboardmouse_m0_playlist_deimos_solo_winter { get; set; }
        public int br_kills_keyboardmouse_m0_playlist_blitz_squad { get; set; }
        public int br_score_keyboardmouse_m0_playlist_respawn_24 { get; set; }
        public int br_kills_keyboardmouse_m0_playlist_defaultsolo { get; set; }
        public int br_matchesplayed_keyboardmouse_m0_playlist_50v50sau { get; set; }
        public int br_matchesplayed_keyboardmouse_m0_playlist_steady_squads { get; set; }
        public int br_matchesplayed_keyboardmouse_m0_playlist_highexplosives_squads { get; set; }
        public int br_minutesplayed_keyboardmouse_m0_playlist_blitz_squad { get; set; }
        public int br_placetop3_keyboardmouse_m0_playlist_highexplosives_squads { get; set; }
        public int br_kills_keyboardmouse_m0_playlist_deimos_duoshow { get; set; }
        public int br_placetop6_keyboardmouse_m0_playlist_toss_squads { get; set; }
        public int br_matchesplayed_keyboardmouse_m0_playlist_50v50he { get; set; }
        public int br_minutesplayed_keyboardmouse_m0_playlist_defaultsolo { get; set; }
        public int br_placetop1_keyboardmouse_m0_playlist_sword_squads { get; set; }
        public int br_placetop1_keyboardmouse_m0_playlist_close_squad { get; set; }
        public int br_placetop6_keyboardmouse_m0_playlist_blitz_squad { get; set; }

        public int br_placetop1_keyboardmouse_m0_playlist_deimos_duo { get; set; }
        public int br_placetop1_keyboardmouse_m0_playlist_score_duo { get; set; }
        public int br_placetop1_keyboardmouse_m0_playlist_blitz_duo { get; set; }
        public int br_placetop1_keyboardmouse_m0_playlist_snipers_duos { get; set; }
        public int br_placetop1_keyboardmouse_m0_playlist_shadownalt_duos { get; set; }

        public int br_minutesplayed_keyboardmouse_m0_playlist_comp_solo { get; set; }
        public int br_placetop1_keyboardmouse_m0_playlist_shadownalt_solo { get; set; }
        public int br_placetop1_keyboardmouse_m0_playlist_snipers_solo { get; set; }
        public int br_minutesplayed_keyboardmouse_m0_playlist_comp_meta_solo { get; set; }
        public int br_minutesplayed_keyboardmouse_m0_playlist_showdown_solo { get; set; }
        public int br_minutesplayed_keyboardmouse_m0_playlist_blitz_solo { get; set; }
        public int br_minutesplayed_keyboardmouse_m0_playlist_deimos_solo { get; set; }
        public int br_minutesplayed_keyboardmouse_m0_playlist_slide_solo { get; set; }
    }
}